out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: peptides-struct
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 3
  dim_inner: 224
  layer_type: specbunnconv
  act: gelu
  residual: True
  dropout: 0.1
bundle:
  bundle_dim: 2
  tau: 1.0
  num_bundle: 16
  num_gnn: 0
  batchnorm: True
  orth_method: householder
  multiscale: True
  gnn_dim: 32
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.2
  base_lr: 0.012
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
