exp:
  exp_name: ['clique']
  wandb: [True]
  num_seeds: [4]
  device: [0]
  seed: [93428]
data:
  dataset: ['clique']
  samples: [100]
  task_type: ['mse_regression']
  eval_metric: ['mse']
  minimize: [True]
  num_nodes: [10]
model:
  model_name: ['bunnnode']
  layer_type: ['SpectralBuNN']
  input_dim: [1]
  hidden_dim: [128]
  out_dim: [1]
  num_layers: [1]
  bundle_dim: [2]
  num_bundle: [1]
  num_gnn_layers: [2]
  gnn_type: ['MLP']
  learn_tau: [False]
  time: [100, 10, 1]
  act: [ 'relu' ]
optim:
  lr: [0.001]
  lr_scheduler: ['ReduceLROnPlateau']
  early_stop: [False]
  epochs: [500]
  batch_size: [1]